///from base of mob/clickon(): (atom/A, params)
#define COMSIG_CLICKON "any_clickon"

#define COMSIG_CANCEL_CLICKON 1

//FLAGS FOR INTERACTIONS WITH OVERMAP OBJECTS
#define OMI_LOCKABLE			(1<<0)

//FLAGS FOR PROPERTIES OF OVERMAP OBJECTS
#define OMP_INDESTRUCTIBLE			(1<<0)
